blank_issues_enabled: false
contact_links:
  - name: Feature Requests & Questions
    url: https://github.com/robcerda/educationaldiscounts/discussions
    about: Please ask and answer questions here.