name: Repository builds and tests
on: [ push, pull_request ]
jobs:

  tests:
    name: Tests
    container: rcerda/educationaldiscounts:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bundle install
        run: |
          bundle config set without jekyll_plugins
          bundle install
      - uses: actions/cache@v2
        with:
          path: |
            /tmp/iso-*.txt
            /tmp/alexa
          key: tmp-files-${{ hashFiles('/tmp/alexa/*')}}
      - name: Change nameserver
        run: echo "nameserver 1.1.1.1" > /etc/resolv.conf
      - name: Validate JSON structure
        run:  bundle exec ruby ./tests/validate-json.rb
      - name: Validate file extensions
        run:  tests/file-extensions.sh
 #     - name: Validate Images
 #       run: bundle exec ruby ./tests/validate-images.rb
      - name: Validate URL/Domain reachability
        run: bundle exec ruby ./tests/validate-urls.rb
        continue-on-error: true
      - name: Quality Checks
        run: bundle exec ruby ./tests/quality-checks.rb
      - name: Validate Ruby scripts
        run: bundle exec rubocop

  build:
    name: Minimal build
    container: rcerda/educationaldiscounts:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bundle install
        run: |
          bundle config set without test
          bundle install
      - name: Build the site
        run: |
          bundle exec ruby ./scripts/join-entries.rb > ./_data/all.json
          bundle exec jekyll build
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Artifact
        if: >
          github.event_name == 'push' &&
          github.ref == 'refs/heads/master' &&
          github.repository == 'robcerda/educationaldiscounts'
        run: tar -czf build.tar.gz .
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: >
          github.event_name == 'push' &&
          github.ref == 'refs/heads/master' &&
          github.repository == 'robcerda/educationaldiscounts'
        with:
          name: build
          path: build.tar.gz

  complete_build:
    name: Complete build
    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/master' &&
      github.repository == 'robcerda/educationaldiscounts'
    needs: [ tests, build ]
    container: rcerda/educationaldiscounts:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - name: Extract artifact
        run: tar -xzf build.tar.gz
      - name: Bundle install
        run: |
          bundle config set without test
          bundle install
      - name: Install GnuPG
        run: apk add --no-cache gnupg
      - uses: crazy-max/ghaction-import-gpg@v4
        id: pgp
        with:
          gpg_private_key: ${{ secrets.pgp_key }}
          passphrase: ${{ secrets.pgp_passphrase }}
      - name: Minify JavaScript files
        run: ./scripts/minify-js.sh
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
          PAGES_REPO_NWO:  ${{ github.repository }}
          PAGES_ENV: production
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JEKYLL_ENV: production
      - name: Create Artifact
        run: tar -czf site.tar.gz _site
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: site.tar.gz

  publish:
    name: Publish build
    needs: [complete_build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: site
      - name: Extract artifact
        run: tar -xzf site.tar.gz
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: _site
          jekyll: false
          fqdn: ${{ secrets.DOMAIN }}
          commit_message: "Deploy ${{GITHUB.SHA}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
